### ISSUE TITLE
Performance goes very bad on macOS

### ISSUE THREAD

**Issue by dsh0416** [heckpsi-lab/em-midori#15]
The benchmark shown in Readme is under Linux instance. But found that performance goes 10 times slower on macOS. Need to be fixed.

**Comment by dsh0416** [comment]
It seems to be an EventMachine issue.
sample code is following
```ruby
require 'eventmachine'
module EchoServer
  def receive_data data
    send_data "HTTP/1.1 200 OK\r\n\r\n"
    close_connection_after_writing
  end
end
EventMachine::run {
  EventMachine::start_server "127.0.0.1", 8081, EchoServer
}
```
Then running:
```bash
wrk -t12 -d60 -c1000 http://127.0.0.1:8081
```
Only 105.41 requests/sec
No that problem in a Linux server.

**Comment by dsh0416** [comment]
Turning off kqueue in EventMachine may get a boost, but still much much slower than epoll in Linux.

**Comment by dsh0416** [comment]
Everything went OK when choosing `ab` instead of `wrk` for benchmarking, still wondering the reason.

**Comment by southwolf** [comment]
I've got a lot of socket errors running a one-minute test using the em script above, and `wrk` results are not stable, varying from 68 to 350, while `ab` gets a stable result (about542 rps).
Seems to be `wrk`'s fault.

**Comment by southwolf** [comment]
The problem might be caused by `-c 1000`, which means keeping 1000 connections open on the same time, not making 1000 requests. After setting `-c 100`, `wrk` gives a quite stable (yet not good) result at 275 qps

**Comment by dsh0416** [comment]
@southwolf Yes, kind of that reason. You could also see that the output gets stucked at some point, causing the terrible average time cost.

**Comment by sodabrew** [comment]
Hi! I'm the maintainer of EventMachine. I'm very interested in helping on this issue. One case where I've also seen poor performance on Mac OS is in eventmachine/eventmachine#607

**Comment by dsh0416** [comment]
@sodabrew I'm very glad to hear that. The easiest way to reproduce the issue is to run the following example, almostly the same as the official code snippet:

```ruby
require 'eventmachine'

module EchoServer
  def receive_data _data
    send_data "HTTP/1.1 200 OK\r\n\r\n"
    close_connection_after_writing
  end
end

EventMachine::run do
  EventMachine::start_server "127.0.0.1", 8081, EchoServer
end
```

In this project, we use the `EM::start_server` to accept connections. I still haven't approached any lower level api to do this. I don't know whether it would help, and I may probably try it in days.

**Comment by dsh0416** [comment]
As we use `nio4r` as new event adapter, the previous discussion is not as useful as it is.

But nio4r still has performance problems because it doesn't use `kqueue` on macOS, further info could be found at https://github.com/socketry/nio4r/issues/125

It is not a high priority issue because few people run production on mac.

We may fix it through developing a new event binding as we've have a general evented adapter now, so that we could switch it painlessly.
