### ISSUE TITLE
CI fails because JRuby doesn't support `set_simultaneous_accept_count` 

### ISSUE THREAD

**Issue by southwolf** [heckpsi-lab/em-midori#17]
JRuby doesn't support `set_simultaneous_accept_count` yet. CI fails after introducing this.

https://github.com/eventmachine/eventmachine/pull/420

**Comment by dsh0416** [comment]
I've forgotten that I'm supporting Jruby

**Comment by dsh0416** [comment]
Fixed by merged PR #18
