### ISSUE TITLE
Attempting to run the benchmark example returns an error

### ISSUE THREAD

**Issue by Hates** [heckpsi-lab/em-midori#27]
Trying to run the example in the benchmark give me the error:

```
undefined method `run' for Midori:Module (NoMethodError)
```

I get the same thing when starting fresh with my own Gemfile etc. I have tried using the Gem from Rubygems as well as pointing my Gemfile directly at the `em-midori` repo. Any ideas? 

```
source "https://rubygems.org"

gem 'em-midori', github: 'heckpsi-lab/em-midori'
```

**Comment by dsh0416** [comment]
The API of server start has changed a little bit since v0.1.0. I've updated the `em-midori-benchmark` project with the latest API. That solve the problem.
