### ISSUE TITLE
feature-req/doc: SVG logo

### ISSUE THREAD

**Issue by Artoria2e5** [heckpsi-lab/em-midori#28]
Make a copy with text elements duplicated, one converted to path and the other hidden with `display: none`.

**Comment by dsh0416** [comment]
I have no idea about text elements duplicated. Could you give some detailed info?

**Comment by Artoria2e5** [comment]
duplicate the element. (

**Comment by dsh0416** [comment]
To duplicate which element?

**Comment by Artoria2e5** [comment]
`<text>` element…

**Comment by dsh0416** [comment]
@Artoria2e5 You mean to generate an SVG version of the logo with both an outlined path and hidden text?

**Comment by Artoria2e5** [comment]
bingo...

**Comment by dsh0416** [comment]
The Logo would be redesigned later, which would provide a better SVG version.
