### ISSUE TITLE
Proposal: Adding benchmark to the repository

### ISSUE THREAD

**Issue by jasl** [heckpsi-lab/em-midori#4]
According to [the topic](https://ruby-china.org/topics/31358), it said that `em-midori` is faster than `rails`, `rails-api` and `sinatra`, even faster than `express.js`, for now `em-midori` is under early development, faster than production-ready frameworks is reasonable, so I propose adding benchmark you showed in the topic to the repository that we can easily observe the performance changing with the framework's developing and research the best scenario.

You can check an [example](https://github.com/macournoyer/thin/tree/master/benchmark) from `thin`

**Comment by dsh0416** [comment]
I've started to write benchmarks, should be able to use in days.

**Comment by dsh0416** [comment]
Init a new [project](https://github.com/heckpsi-lab/em-midori-benchmark) for benchmark.
